apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
  namespace: arc-runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
        - name: buildkitd
          image: moby/buildkit:rootless
          args: ["buildkitd", "--addr", "tcp://0.0.0.0:1234", "--oci-worker-no-process-sandbox"]
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          ports:
            - containerPort: 1234
          securityContext:
            runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: arc-runners
spec:
  selector:
    app: buildkitd
  ports:
    - name: buildkit
      port: 1234
      targetPort: 1234
